<a href="https://colab.research.google.com/github/navkapil/googlecolab/blob/master/testneuralnettorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn

In [5]:
x = torch.rand([5,3])

In [6]:
print(x)

tensor([[0.1255, 0.4917, 0.6697],
        [0.7998, 0.3996, 0.7058],
        [0.0704, 0.6394, 0.8943],
        [0.2087, 0.0446, 0.8783],
        [0.1825, 0.4769, 0.4000]])


In [7]:
X = torch.tensor(([2, 9], [1, 5], [3, 6]), dtype=torch.float) # 3 X 2 tensor
y = torch.tensor(([[92]], [[100]], [[89]]), dtype=torch.float) # 3 X 1 tensor
xPredicted = torch.tensor(([4, 8]), dtype=torch.float) # 1 X 2 tensor

In [8]:
print(xPredicted.size())

torch.Size([2])


In [9]:
# scale units
X_max, _ = torch.max(X, 0)
print(X_max)
print(_)
xPredicted_max, _ = torch.max(xPredicted, 0)

print(xPredicted_max)
print(_)
X = torch.div(X, X_max)
xPredicted = torch.div(xPredicted, xPredicted_max)
print(xPredicted)
y = y / 100  # max test score is 100
print(y)


tensor([3., 9.])
tensor([2, 0])
tensor(8.)
tensor(1)
tensor([0.5000, 1.0000])
tensor([[[0.9200]],

        [[1.0000]],

        [[0.8900]]])


In [10]:
print(_)

tensor(1)


In [11]:
a = torch.randn(4, 4)
print(a)
print(torch.max(a))
print(torch.max(a,0))
print(torch.max(a,1))

tensor([[ 0.5133,  2.0931, -1.2305, -0.7245],
        [ 1.3396,  1.3410,  0.2717, -0.0973],
        [-2.0923,  0.3664,  1.0164,  0.1754],
        [-3.2838,  1.5086, -1.2314, -0.1353]])
tensor(2.0931)
torch.return_types.max(
values=tensor([1.3396, 2.0931, 1.0164, 0.1754]),
indices=tensor([1, 0, 2, 2]))
torch.return_types.max(
values=tensor([2.0931, 1.3410, 1.0164, 1.5086]),
indices=tensor([1, 1, 2, 1]))


In [3]:
class Neural_Network(nn.Module):
    def __init__(self, ):
        super(Neural_Network, self).__init__()
        # parameters
        # TODO: parameters can be parameterized instead of declaring them here
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
        # weights
        self.W1 = torch.randn(self.inputSize, self.hiddenSize) # 2 X 3 tensor
        self.W2 = torch.randn(self.hiddenSize, self.outputSize) # 3 X 1 tensor
        
    def forward(self, X):
        print("In forward")
        self.z = torch.matmul(X, self.W1) # 3 X 3 ".dot" does not broadcast in PyTorch
        print(self.z)
        self.z2 = self.sigmoid(self.z) # activation function
        print("Output of hidden layer --")
        print(self.z2)
        self.z3 = torch.matmul(self.z2, self.W2)
        print(self.z3)
        o = self.sigmoid(self.z3) # final activation function
        print("the output is-")
        print(o)
        return o
        
    def sigmoid(self, s):
        return 1 / (1 + torch.exp(-s))
    
    def sigmoidPrime(self, s):
        # derivative of sigmoid
        return s * (1 - s)
    
    def backward(self, X, y, o):
        self.o_error = y - o # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # derivative of sig to error
        self.z2_error = torch.matmul(self.o_delta, torch.t(self.W2))
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.z2)
        self.W1 += torch.matmul(torch.t(X), self.z2_delta)
        self.W2 += torch.matmul(torch.t(self.z2), self.o_delta)
        
    def train(self, X, y):
        # forward + backward pass for training
        o = self.forward(X)
        self.backward(X, y, o)
        
    def saveWeights(self, model):
        # we will use the PyTorch internal storage functions
        torch.save(model, "NN")
        # you can reload model with all the weights and so forth with:
        # torch.load("NN")
        
    def predict(self):
        print ("Predicted data based on trained weights: ")
        print ("Input (scaled): \n" + str(xPredicted))
        print ("Output: \n" + str(self.forward(xPredicted)))

In [13]:
nn1 = Neural_Network()
nn1.forward(torch.ones([1,2]))

In forward
tensor([[-0.8696, -1.8627,  1.8113]])
Output of hidden layer --
tensor([[0.2953, 0.1344, 0.8595]])
tensor([[-0.5148]])
the output is-
tensor([[0.3741]])


tensor([[0.3741]])

In [14]:
print(nn1.W1)

tensor([[-1.0846, -0.3387,  1.0543],
        [ 0.2150, -1.5240,  0.7570]])


In [15]:
nn1.sigmoid(torch.zeros([2,1]))

tensor([[0.5000],
        [0.5000]])

In [16]:
nn1(X)

In forward
tensor([[-0.5081, -1.7498,  1.4598],
        [-0.2421, -0.9595,  0.7720],
        [-0.9413, -1.3547,  1.5589]])
Output of hidden layer --
tensor([[0.3756, 0.1481, 0.8115],
        [0.4398, 0.2770, 0.6839],
        [0.2806, 0.2051, 0.8262]])
tensor([[-0.5658],
        [-0.6001],
        [-0.5055]])
the output is-
tensor([[0.3622],
        [0.3543],
        [0.3762]])


tensor([[0.3622],
        [0.3543],
        [0.3762]])

In [19]:
nn1.train(X,-1)

In forward
tensor([[-0.5081, -1.7498,  1.4598],
        [-0.2421, -0.9595,  0.7720],
        [-0.9413, -1.3547,  1.5589]])
Output of hidden layer --
tensor([[0.3756, 0.1481, 0.8115],
        [0.4398, 0.2770, 0.6839],
        [0.2806, 0.2051, 0.8262]])
tensor([[-0.5658],
        [-0.6001],
        [-0.5055]])
the output is-
tensor([[0.3622],
        [0.3543],
        [0.3762]])


In [21]:
nn1.predict()

Predicted data based on trained weights: 
Input (scaled): 
tensor([0.5000, 1.0000])
In forward
tensor([-0.1469, -1.6656,  1.3344])
Output of hidden layer --
tensor([0.4633, 0.1590, 0.7916])
tensor([-1.4032])
the output is-
tensor([0.1973])
Output: 
tensor([0.1973])
