<a href="https://colab.research.google.com/github/navkapil/googlecolab/blob/master/test001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.rand([5,3])

In [3]:
print(x)

tensor([[0.1818, 0.9768, 0.4555],
        [0.6309, 0.7733, 0.2909],
        [0.0496, 0.9206, 0.1040],
        [0.7252, 0.5955, 0.9787],
        [0.7891, 0.9705, 0.8345]])


In [18]:
X = torch.tensor(([2, 9], [1, 5], [3, 6]), dtype=torch.float) # 3 X 2 tensor
y = torch.tensor(([[92]], [[100]], [[89]]), dtype=torch.float) # 3 X 1 tensor
xPredicted = torch.tensor(([4, 8]), dtype=torch.float) # 1 X 2 tensor

In [19]:
print(xPredicted.size())

torch.Size([2])


In [25]:
# scale units
X_max, _ = torch.max(X, 0)
print(X_max)
print(_)
xPredicted_max, _ = torch.max(xPredicted, 0)

print(xPredicted_max)
print(_)
X = torch.div(X, X_max)
xPredicted = torch.div(xPredicted, xPredicted_max)
print(xPredicted)
y = y / 100  # max test score is 100
print(y)


tensor([1., 1.])
tensor([2, 0])
tensor(1.)
tensor(1)
tensor([0.5000, 1.0000])
tensor([[[0.9200]],

        [[1.0000]],

        [[0.8900]]])


In [26]:
print(_)

tensor(1)


In [28]:
a = torch.randn(4, 4)
print(a)
print(torch.max(a))
print(torch.max(a,0))
print(torch.max(a,1))

tensor([[ 0.5378,  0.6911, -0.3741, -1.5628],
        [-1.0705, -0.8962, -0.8219, -0.3602],
        [ 1.3557, -0.9273,  0.5753, -1.1687],
        [ 0.5541,  0.4619, -1.5173,  0.1382]])
tensor(1.3557)
torch.return_types.max(
values=tensor([1.3557, 0.6911, 0.5753, 0.1382]),
indices=tensor([2, 0, 2, 3]))
torch.return_types.max(
values=tensor([ 0.6911, -0.3602,  1.3557,  0.5541]),
indices=tensor([1, 3, 0, 0]))


In [30]:
class Neural_Network(nn.Module):
    def __init__(self, ):
        super(Neural_Network, self).__init__()
        # parameters
        # TODO: parameters can be parameterized instead of declaring them here
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
        # weights
        self.W1 = torch.randn(self.inputSize, self.hiddenSize) # 2 X 3 tensor
        self.W2 = torch.randn(self.hiddenSize, self.outputSize) # 3 X 1 tensor
        
    def forward(self, X):
        self.z = torch.matmul(X, self.W1) # 3 X 3 ".dot" does not broadcast in PyTorch
        self.z2 = self.sigmoid(self.z) # activation function
        self.z3 = torch.matmul(self.z2, self.W2)
        o = self.sigmoid(self.z3) # final activation function
        return o
        
    def sigmoid(self, s):
        return 1 / (1 + torch.exp(-s))
    
    def sigmoidPrime(self, s):
        # derivative of sigmoid
        return s * (1 - s)
    
    def backward(self, X, y, o):
        self.o_error = y - o # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # derivative of sig to error
        self.z2_error = torch.matmul(self.o_delta, torch.t(self.W2))
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.z2)
        self.W1 += torch.matmul(torch.t(X), self.z2_delta)
        self.W2 += torch.matmul(torch.t(self.z2), self.o_delta)
        
    def train(self, X, y):
        # forward + backward pass for training
        o = self.forward(X)
        self.backward(X, y, o)
        
    def saveWeights(self, model):
        # we will use the PyTorch internal storage functions
        torch.save(model, "NN")
        # you can reload model with all the weights and so forth with:
        # torch.load("NN")
        
    def predict(self):
        print ("Predicted data based on trained weights: ")
        print ("Input (scaled): \n" + str(xPredicted))
        print ("Output: \n" + str(self.forward(xPredicted)))

In [31]:
nn1 = Neural_Network()

In [32]:
print(nn1.W1)

tensor([[-5.9945e-04, -7.6638e-01, -1.9350e-01],
        [-9.1975e-01, -2.4725e-04,  2.5673e+00]])


In [36]:
nn1.sigmoid(torch.zeros([2,1]))

tensor([[0.5000],
        [0.5000]])