<a href="https://colab.research.google.com/github/navkapil/googlecolab/blob/master/test001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.rand([5,3])

In [3]:
print(x)

tensor([[0.1818, 0.9768, 0.4555],
        [0.6309, 0.7733, 0.2909],
        [0.0496, 0.9206, 0.1040],
        [0.7252, 0.5955, 0.9787],
        [0.7891, 0.9705, 0.8345]])


In [18]:
X = torch.tensor(([2, 9], [1, 5], [3, 6]), dtype=torch.float) # 3 X 2 tensor
y = torch.tensor(([[92]], [[100]], [[89]]), dtype=torch.float) # 3 X 1 tensor
xPredicted = torch.tensor(([4, 8]), dtype=torch.float) # 1 X 2 tensor

In [19]:
print(xPredicted.size())

torch.Size([2])


In [25]:
# scale units
X_max, _ = torch.max(X, 0)
print(X_max)
print(_)
xPredicted_max, _ = torch.max(xPredicted, 0)

print(xPredicted_max)
print(_)
X = torch.div(X, X_max)
xPredicted = torch.div(xPredicted, xPredicted_max)
print(xPredicted)
y = y / 100  # max test score is 100
print(y)


tensor([1., 1.])
tensor([2, 0])
tensor(1.)
tensor(1)
tensor([0.5000, 1.0000])
tensor([[[0.9200]],

        [[1.0000]],

        [[0.8900]]])


In [26]:
print(_)

tensor(1)


In [28]:
a = torch.randn(4, 4)
print(a)
print(torch.max(a))
print(torch.max(a,0))
print(torch.max(a,1))

tensor([[ 0.5378,  0.6911, -0.3741, -1.5628],
        [-1.0705, -0.8962, -0.8219, -0.3602],
        [ 1.3557, -0.9273,  0.5753, -1.1687],
        [ 0.5541,  0.4619, -1.5173,  0.1382]])
tensor(1.3557)
torch.return_types.max(
values=tensor([1.3557, 0.6911, 0.5753, 0.1382]),
indices=tensor([2, 0, 2, 3]))
torch.return_types.max(
values=tensor([ 0.6911, -0.3602,  1.3557,  0.5541]),
indices=tensor([1, 3, 0, 0]))
