<a href="https://colab.research.google.com/github/navkapil/googlecolab/blob/master/testneuralnettorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.rand([5,3])

In [3]:
print(x)

tensor([[0.7227, 0.7687, 0.8792],
        [0.7395, 0.7416, 0.1451],
        [0.9433, 0.5178, 0.7514],
        [0.9370, 0.5633, 0.9597],
        [0.8568, 0.7078, 0.6316]])


In [4]:
X = torch.tensor(([2, 9], [1, 5], [3, 6]), dtype=torch.float) # 3 X 2 tensor
y = torch.tensor(([[92]], [[100]], [[89]]), dtype=torch.float) # 3 X 1 tensor
xPredicted = torch.tensor(([4, 8]), dtype=torch.float) # 1 X 2 tensor

In [5]:
print(xPredicted.size())

torch.Size([2])


In [6]:
# scale units
X_max, _ = torch.max(X, 0)
print(X_max)
print(_)
xPredicted_max, _ = torch.max(xPredicted, 0)

print(xPredicted_max)
print(_)
X = torch.div(X, X_max)
xPredicted = torch.div(xPredicted, xPredicted_max)
print(xPredicted)
y = y / 100  # max test score is 100
print(y)


tensor([3., 9.])
tensor([2, 0])
tensor(8.)
tensor(1)
tensor([0.5000, 1.0000])
tensor([[[0.9200]],

        [[1.0000]],

        [[0.8900]]])


In [7]:
print(_)

tensor(1)


In [8]:
a = torch.randn(4, 4)
print(a)
print(torch.max(a))
print(torch.max(a,0))
print(torch.max(a,1))

tensor([[ 1.0740,  0.6390,  0.1764,  0.3377],
        [ 0.7792,  1.1271, -0.1719, -0.0176],
        [-0.4608, -0.1294, -0.6571,  1.1918],
        [ 1.6136,  1.3391,  0.2827, -0.5574]])
tensor(1.6136)
torch.return_types.max(
values=tensor([1.6136, 1.3391, 0.2827, 1.1918]),
indices=tensor([3, 3, 3, 2]))
torch.return_types.max(
values=tensor([1.0740, 1.1271, 1.1918, 1.6136]),
indices=tensor([0, 1, 3, 0]))


In [9]:
class Neural_Network(nn.Module):
    def __init__(self, ):
        super(Neural_Network, self).__init__()
        # parameters
        # TODO: parameters can be parameterized instead of declaring them here
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
        # weights
        self.W1 = torch.randn(self.inputSize, self.hiddenSize) # 2 X 3 tensor
        self.W2 = torch.randn(self.hiddenSize, self.outputSize) # 3 X 1 tensor
        
    def forward(self, X):
        print("In forward")
        self.z = torch.matmul(X, self.W1) # 3 X 3 ".dot" does not broadcast in PyTorch
        print(self.z)
        self.z2 = self.sigmoid(self.z) # activation function
        print("Output of hidden layer --")
        print(self.z2)
        self.z3 = torch.matmul(self.z2, self.W2)
        print(self.z3)
        o = self.sigmoid(self.z3) # final activation function
        print("the output is-")
        print(o)
        return o
        
    def sigmoid(self, s):
        return 1 / (1 + torch.exp(-s))
    
    def sigmoidPrime(self, s):
        # derivative of sigmoid
        return s * (1 - s)
    
    def backward(self, X, y, o):
        self.o_error = y - o # error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # derivative of sig to error
        self.z2_error = torch.matmul(self.o_delta, torch.t(self.W2))
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.z2)
        self.W1 += torch.matmul(torch.t(X), self.z2_delta)
        self.W2 += torch.matmul(torch.t(self.z2), self.o_delta)
        
    def train(self, X, y):
        # forward + backward pass for training
        o = self.forward(X)
        self.backward(X, y, o)
        
    def saveWeights(self, model):
        # we will use the PyTorch internal storage functions
        torch.save(model, "NN")
        # you can reload model with all the weights and so forth with:
        # torch.load("NN")
        
    def predict(self):
        print ("Predicted data based on trained weights: ")
        print ("Input (scaled): \n" + str(xPredicted))
        print ("Output: \n" + str(self.forward(xPredicted)))

In [10]:
nn1 = Neural_Network()
nn1.forward(torch.ones([1,2]))

In forward
tensor([[-1.2166, -2.2231, -1.2381]])
Output of hidden layer --
tensor([[0.2285, 0.0977, 0.2248]])
tensor([[-0.2164]])
the output is-
tensor([[0.4461]])


tensor([[0.4461]])

In [11]:
print(nn1.W1)

tensor([[-0.3854, -0.3652, -1.0576],
        [-0.8312, -1.8579, -0.1805]])


In [12]:
nn1.sigmoid(torch.zeros([2,1]))

tensor([[0.5000],
        [0.5000]])

In [13]:
nn1(X)

In forward
tensor([[-1.0881, -2.1014, -0.8856],
        [-0.5902, -1.1539, -0.4528],
        [-0.9395, -1.6038, -1.1779]])
Output of hidden layer --
tensor([[0.2520, 0.1090, 0.2920],
        [0.3566, 0.2398, 0.3887],
        [0.2810, 0.1675, 0.2354]])
tensor([[-0.2491],
        [-0.3662],
        [-0.2673]])
the output is-
tensor([[0.4380],
        [0.4095],
        [0.4336]])


tensor([[0.4380],
        [0.4095],
        [0.4336]])

In [14]:
nn1.train(X,-1)

In forward
tensor([[-1.0881, -2.1014, -0.8856],
        [-0.5902, -1.1539, -0.4528],
        [-0.9395, -1.6038, -1.1779]])
Output of hidden layer --
tensor([[0.2520, 0.1090, 0.2920],
        [0.3566, 0.2398, 0.3887],
        [0.2810, 0.1675, 0.2354]])
tensor([[-0.2491],
        [-0.3662],
        [-0.2673]])
the output is-
tensor([[0.4380],
        [0.4095],
        [0.4336]])


In [15]:
nn1.predict()

Predicted data based on trained weights: 
Input (scaled): 
tensor([0.5000, 1.0000])
In forward
tensor([-0.8816, -2.0070, -0.6561])
Output of hidden layer --
tensor([0.2928, 0.1185, 0.3416])
tensor([-0.5090])
the output is-
tensor([0.3754])
Output: 
tensor([0.3754])
